spring:
  application:
    name: gateway-server
  profiles:
    active: @env@
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      routes:
        - id: seckill-server
          uri: lb://seckill-server
          predicates:
            - Path=/seckill/**
        - id: general-server
          uri: lb://general-server
          predicates:
            - Path=/general/**



