server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.20.49:8848
      config:
        server-addr: 120.79.20.49:8848
  datasource:
    url:  jdbc:mysql://localhost:3306/zj_auction?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yangbing
  redis:
    port: 6379
    host: 120.79.20.49
    username: root
    timeout: 3000
    lettuce:
      pool:
        max-active: 128
        min-idle: 16
        max-idle: 64
        max-wait: -1
    password: zhongjiu_test
  rabbitmq:
    addresses: 120.79.20.49:5672
    username: admin
    password: zhongjiu_test

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
