---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangbing.
--- DateTime: 2022/5/26 22:08
---
-- inventoryDecrAndLPopSNScript
if ((redis.call('exists', KEYS[1]) == 1) and (redis.call('exists', KEYS[2]) == 1)) then
    if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > 0) then
        redis.call('hincrby', KEYS[1], ARGV[1], -1)
        return redis.call('LPOP', KEYS[2]);
    end;
    return nil;
end;
return nil;

-- 2022-05-29 简化版本 v1
-- if ((redis.call('exists', KEYS[1]) == 1) and (redis.call('exists', KEYS[2]) == 1)) then if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > 0) then redis.call('hincrby', KEYS[1], ARGV[1], -1) return redis.call('LPOP', KEYS[2]); end; return nil; end; return nil;
if ((redis.call('exists', KEYS[1]) == 1) and (redis.call('exists', KEYS[2]) == 1)) then
    if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > 0) then
        redis.call('hincrby', KEYS[1], ARGV[1], -1)
        return redis.call('LPOP', KEYS[2]);
    end;
    return nil;
end;
return nil;

-- 2022-05-29 支持一次锁定一个库存
-- if ((redis.call('exists', KEYS[1]) == 1) and (redis.call('exists', KEYS[2]) == 1)) then if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > tonumber(ARGV[2])) then redis.call('hincrby', KEYS[1], ARGV[1], -ARGV[2]) return redis.call('LPOP', KEYS[2]); end; return nil;end;return nil;

-- "if ((redis.call('exists', KEYS[1]) == 1) and (redis.call('exists', KEYS[2]) == 1)) then if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > 0) then redis.call('hincrby', KEYS[1], ARGV[1], -ARGV[3])return redis.call('LPOP', KEYS[2]);end;return nil;end;return nil;"
-- a1b4d39b78f9ee7c73e6f6d9a681b0f8be081d74

-- inventoryDecrScript:v1  库存不足:-1,成功:1,失败:0;
if (redis.call('exists', KEYS[1]) == 1) then
    if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > 0) then
       return redis.call('hincrby', KEYS[1], ARGV[1], -ARGV[3]);
    end;
    return -1;
end;
return -1;

-- v1: 余量
-- "if (redis.call('exists', KEYS[1]) == 1) then if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > tonumber(ARGV[2])) then return redis.call('hincrby', KEYS[1], ARGV[1], -ARGV[3]); end; return -1; end; return -1;"

-- 暂时成功版本
-- eval "if (redis.call('exists', KEYS[1]) == 1) then if(tonumber(redis.call('hget', KEYS[1], ARGV[1])) > tonumber(ARGV[2])) then return redis.call('hincrby', KEYS[1], ARGV[1], -ARGV[3]); end; return 0; end; return 0;" 1 myhash flower1 99 3